backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"
media_library:
  name: images

collections:
  - name: "event"
    label: "Event"
    folder: "src/event"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Event Title", name: "title", widget: "string" }
      - { label: "Event Type", name: "type", widget: "string" }
      - { label: "Event Description", name: "description", widget: "markdown" }
      - { label: "Event Date", name: "date", widget: "datetime" }
