backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "event"
    label: "Events"
    folder: "src/event"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Event Title", name: "title", widget: "string" }
      - { label: "Event Type", name: "type", widget: "string" }
      - { label: "Event Description", name: "description", widget: "markdown" }
      - { label: "Event Date", name: "date", widget: "datetime" }
      - { label: "Event Time", name: "time", widget: "string" }

  - name: "background images"
    label: "Background Images"
    folder: "src/background-images"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }

  - name: "banner"
    label: "Banner Paragraph"
    folder: "src/banner"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Paragraph Number", name: "title", widget: "string" }
      - { label: "Paragraph", name: "description", widget: "markdown" }

  - name: "video"
    label: "Videos"
    folder: "src/videos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Videos"
        name: "video"
        widget: "file"
        media_library:
          config:
            multiple: true

  - name: "team image"
    label: "Team Picture"
    folder: "src/team-img"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Picture", name: "title", widget: "image" }
